### PR TITLE
First approx to get a fixture to invoke a builder method of class to

### PR DESCRIPTION
**Pull request by josejuanmontiel**
I'm trying to use with bean create by gRPC (google protobuffer) that has no public constructor because implement by its self a builder pattern...

I saw the option to "Arguments constructor bean", but not the option to invoke the builder method.

It's a simple pull request that implements this fixture.

### CODE REVIEW

**Comment by keepcosmos** [comment]
Please check CI :)

**Comment by keepcosmos** [comment]
I think supporting grpc through extension like`beanmother-java8-converter` or `beanmother-joda-time-converter` does, because builder pattern of grpc has it's own convention. what do you think?

**Comment by josejuanmontiel** [comment]
hi, sorry for the broken build, it's prettend to be a dialog, not a final aprox.
I fix the build, only a reorganize need to be perform.
Later i can review the "pluggin aprox" (and the coverage 0.1% down :)

**Comment by keepcosmos** [comment]
Thanks!! 👍

**Comment by josejuanmontiel** [comment]
Hi, take a look to the new aproach, it's a WIP with a real class "grpc-builder-pattern-like"... but i don't understand how to fit inside mapper pluggin concept like beanmother-java8-converter... i'll give a try later... but please review the aproach. thanks.

**Comment by keepcosmos** [comment]
My approach is, 

1. Create grpc-mapper submodule.
2. Implement GRPCBuilderFixtureMapper from `AbstractFixtureMapper` like `SetterAndFieldFixtureMapper`
3. Modify `AbstractBeanMother` and `BeanMother` class for switching between `SetterAndFieldFixtureMapper` or `GRPCBuilderFixtureMapper` or Create new `GRPCObjectMother` class.

What do you think?

**Comment by josejuanmontiel** [comment]
I do a rework... and...

1º Do the module and undo the other aprox.
2º I think if i implement last point, it's not necesary.
3º Implement GRPCObjectMother extends AbstractBeanMother, and expose some internals of the api.

From the distance, i think it's the more accurate to your proposal

But i don't know if would be better hide the "switch" according to the existence of the params of the fixture..

I'm still interesting in doing a good PR :+1:

**Comment by keepcosmos** [comment]
Thanks, I'm on vacation. So, I will check ASAP 😄

**Comment by keepcosmos** [comment]
You are right! good PR, Could you write more test cases about builder casses from GRPC?

**Comment by josejuanmontiel** [comment]
A minimal reoganize... WIP if i have more time ;) let me think in more test, maybe another "builder pattern" that can be implement in this way...

**Comment by josejuanmontiel** [comment]
Hi, i upload a few more examples in the fixture file with and without the params. @keepcosmos Could you accept the pull request? Thanks.

**Comment by josejuanmontiel** [comment]
Please review the #17 hope this could be ok.

**Pull request merged**
