### PR TITLE
Singlepageintro

### PR DESCRIPTION
**Pull request by bhaskarmac**
Hi @keepcosmos ,

Created single HTML page with README.md content and navigation as per given reference links.

Please check and accept the Pull request

### CODE REVIEW

**Comment by keepcosmos** [comment]
Thanks :)
Could you change path to `/docs`?
Github page supports `/docs` not `/doc`

**Comment by keepcosmos** [comment]
Thanks, I checked the page. It totally same as natty page that I wrote as a example.

I have no idea we can copy the whole page. I think we should find a open license template  .

**Comment by bhaskarmac** [comment]
@keepcosmos  Oh okay, So can I redesign the page or can we make some other changes to the existing page which is currently I have submitted?

**Comment by bhaskarmac** [comment]
@keepcosmos  I have just added index2.html page which will generate the static single page documentation using the README.md file from the repo. This index2.html will be runtime rendered by using docsify (https://github.com/QingWei-Li/docsify-cli) Is this okay? please check and let me know.

**Comment by keepcosmos** [comment]
Thanks! docsify looks good, but how can I open page on my local machine

**Comment by bhaskarmac** [comment]
Just copy index2.html on the local machine and open it in the browser it will show the generated documentation page by using the README.md in the repo.  Please let me know Can I remove the index.html and CSS file?

**Comment by bhaskarmac** [comment]
@keepcosmos Removed the old index page and CSS. Added page generating with the docsify. Please check and accept the Pull request.

**Comment by keepcosmos** [comment]
Is it all done? please rebase your commits

**Comment by bhaskarmac** [comment]
@keepcosmos Please check rebase completed

**Comment by keepcosmos** [comment]
@bhaskarmac Sorry, I mean you should squash commits so, make as a single commit for readable history.

**Comment by bhaskarmac** [comment]
@keepcosmos  Please check now 👍

**Comment by keepcosmos** [comment]
@bhaskarmac Thanks! <3

**Comment by bhaskarmac** [comment]
@keepcosmos  You're welcome :) Happy to help.

**Comment by keepcosmos** [comment]
@bhaskarmac Just published check http://beanmother.io !!

**Comment by bhaskarmac** [comment]
Looks fantastic :) 👍

**Pull request merged**
